Fix potentially cause a memory leak in EF
fail: Confab.Shared.Infrastructure.Queries.QueryDispatcher[0]

The client projection contains a reference to a constant expression of 'Confab.Modules.Agendas.Infrastructure.EF.Queries.Handlers.BrowseAgendaItemsHandler' through the instance method 'AsDto'. This could potentially cause a memory leak; consider making the method static so that it does not capture constant in the instance.

See https://go.microsoft.com/fwlink/?linkid=2103067 for more information.;

Query: 'BrowsAgendaItems { ConferenceId = 26914b94-ce02-474d-bb8c-24d5b0470fca }'.

System.InvalidOperationException: The client projection contains a reference to a constant expression of 'Confab.Modules.Agendas.Infrastructure.EF.Queries.Handlers.BrowseAgendaItemsHandler' through the instance method 'AsDto'. This could potentially cause a memory leak; consider making the method static so that it does not capture constant in the instance. See https://go.microsoft.com/fwlink/?linkid=2103067 for more information.
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.ConstantVerifyingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
         at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VerifyNoClientConstant(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
         at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
         at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
         at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
         at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
         at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
         at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
         at Confab.Modules.Agendas.Infrastructure.EF.Queries.Handlers.BrowseAgendaItemsHandler.HandleAsync(BrowsAgendaItems query) in C:\g\Confab\src\Modules\Agendas\Confab.Modules.Agendas.Infrastructure\EF\Queries\Handlers\BrowseAgendaItemsHandler.cs:line 22
         at
	 Confab.Shared.Infrastructure.Queries.QueryDispatcher.QueryAsync[TResult](IQuery`1
	 query) in
	 C:\g\Confab\src\Shared\Confab.Shared.Infrastructure\Queries\QueryDispatcher.cs:line
	 30